apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-prd
  name: nginx-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prd
  template:
    metadata:
      labels:
        app: nginx-prd
    spec:
      containers:
      - image: nginx
        name: nginx-prd
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "256m"
