apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-prd
spec:
  ports:
  - name: 80-80
    nodePort: 30082
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
