apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-prometheus-integration
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: '14.11.0' # chart version, not Prometheus version
    helm:
      values: |
        alertmanager:
          enabled: false
        alertmanagerFiles:
          alertmanager.yml: ""
        nodeExporter:
          enabled: false
        pushgateway:
          enabled: false
          serverFiles:
        prometheus:
          prometheusSpec:
            additionalScrapeConfigs:
              - job_name: kube-prometheus/sst-microservices

                scrape_interval: 30s
                scrape_timeout: 10s
                metrics_path: /metrics
                scheme: http

                kubernetes_sd_configs:
                  - api_server: null
                    role: endpoints
                    namespaces:
                      names:
                        - default

                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                    regex: true
                    action: keep
                  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                    action: replace
                    regex: ([^:]+)(?::\d+)?;(\d+)
                    replacement: $1:$2
                    target_label: __address__
                  - source_labels: [__meta_kubernetes_service_name]
                    separator: ;
                    regex: (.*)
                    target_label: service
                    replacement: $1
                    action: replace
                  - source_labels: [__meta_kubernetes_pod_name]
                    separator: ;
                    regex: (.*)
                    target_label: pod
                    replacement: $1
                    action: replace
  destination:
    namespace: default
  syncPolicy:
    automated: {}
