
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-stg
  name: nginx-stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-stg
  template:
    metadata:
      labels:
        app: nginx-stg
    spec:
      containers:
      - image: nginx
        name: nginx-stg
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "256m"
