apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd
spec:
  generators:
  - list:
      elements:
      - cluster: cluster1
        url: https://kubernetes.default.svc
     - cluster: cluster2
        url: https://kubernetes.default.svc
      - cluster: cluster3
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-bgd'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/christianh814/gitops-examples
        targetRevision: master
        path: applicationsets/list-generator/overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: argocd
