apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-nginx-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
generators:
- list:
    elements:
    - env: stg
    - env: prd
spec:
  project: config
  source:
    repoURL: https://github.com/fatgit/gitops
    targetRevision: HEAD
    path: service/{{env}}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
