apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-nginx-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: config
  source:
    repoURL: https://github.com/fatgit/gitops
    targetRevision: HEAD
    path: service/prd
  destination:
    namespace: argocd
  syncPolicy:
    automated: {}
